# 1. Handle the "root" (domain.com/) by sending it to domain.com/en
root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_home
        _locale: en
        permanent: false

# 2. Automatically prefix ALL controllers with /{_locale}
app_localized:
    resource: ../src/Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: en

# controllers:
#     resource: routing.controllers
#     type: attribute


